#created on: 24-Sep-2007
package ItemsRules3

#imports
import com.sapienter.jbilling.server.item.PricingField
import com.sapienter.jbilling.server.item.db.ItemDTO
import com.sapienter.jbilling.server.order.db.OrderLineDTO;
import com.sapienter.jbilling.server.item.tasks.RulesItemManager.OrderManager

#globals
global com.sapienter.jbilling.server.item.tasks.RulesItemManager.OrderManager order;

rule "Lemon and Coffee discount"
	when
	    exists ItemDTO(id == 2) # Lemonade
	    exists ItemDTO(id == 3) # Coffee
	then
	    order.addItem(14); # 10% discount
end

rule 'rateOrder test1'
	dialect "java"
when
	$field : PricingField( name == "add" )
	$line  : OrderLineDTO( )
then
	$line.setPrice((float)($line.getPrice() + $field.getDoubleValue()));
end

rule 'rateOrder test2'
	dialect "java"
when
	$field : PricingField( name == "subtract" )
	$line  : OrderLineDTO( )
then
	$line.setPrice((float)($line.getPrice() - $field.getDoubleValue()));
end
