#created on: 24-Sep-2007
package ItemsRules3

#imports
import com.sapienter.jbilling.server.item.ItemDTOEx
import com.sapienter.jbilling.server.item.tasks.RulesItemManager.OrderManager

#globals
global com.sapienter.jbilling.server.item.tasks.RulesItemManager.OrderManager order;

rule "Lemon and Coffee discount"
	when
	    exists ItemDTOEx(id == "2") # Lemonade
	    exists ItemDTOEx(id == "3") # Coffee
	then
	    order.addItem(14); # 10% discount
end

