package Mediation
import com.sapienter.jbilling.server.item.PricingField
import com.sapienter.jbilling.server.mediation.task.RulesMediationTask.ProcessManager

global com.sapienter.jbilling.server.mediation.task.RulesMediationTask.ProcessManager mediationManager;

function int convert_to_minutes(Integer seconds) {
	return ((int)  Math.ceil(seconds / 60)) + 1;
}



rule 'user setter'
when 
    $field : PricingField( name == "userfield")
    ProcessManager()
then 
   mediationManager.setUserFromUsername($field.getStrValue());

end

rule 'line creation'
when 
    $field : PricingField( name == "duration")
    ProcessManager()
then
    mediationManager.addLine(1, $field.getIntValue());

end



rule 'date setter'
when 
    $field : PricingField( name == "start")
    ProcessManager()
then 
   mediationManager.setEventDate($field.getDateValue());

end

